spring:
  port: 8080
  servlet:
    context-path: /
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    password: root
    url: jdbc:mysql://127.0.0.1:3306/veyhub
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    